### ISSUE TITLE
Role type seems to be unwritable in SCIM provisioning

### ISSUE THREAD

**Issue by music** [MicrosoftDocs/entra-docs#391] opened 2024-02-15 20:41 UTC
Hi,

I am currently trying to integrate a new application using SCIM roles. To do this, I set up custom roles for my app, assigned them to users, and then configured my roles attribute mapping using `SingleAppRoleAssignment([appRoleAssignments])` in the Provisioning options. However, I'm seeing an inconsistency in which role property I try to assign the app role to.

If I try to map `SingleAppRoleAssignment([appRoleAssignments])` to `roles[primary eq "True"].type`, I see this in my SCIM request on my server:
```
{
  ...,
  roles: [{
    "primary": true,
    "type": "WindowsAzureActiveDirectoryRole",
  }],
}
```

But if I map `SingleAppRoleAssignment([appRoleAssignments])` (let's say that evaluates to `ADMIN` for this example) to `roles[primary eq "True"].value`, I see this:
```
{
  ...,
  roles: [{
    "primary": true,
    "type": "WindowsAzureActiveDirectoryRole",
    "value": "ADMIN",
  }],
}
```

This implies that either `roles[primary eq "True"].type` is not writable, or it is mapped but then later overwritten later by a setting I'm not aware of. Could I get some clarification? As far as I could find, this behavior is not documented anywhere, so I decided to file as an issue in case this was a bug on the Entra side.

Thanks in advance,
Cameron

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b07a9e-5e16-32ed-265e-32a32998ce37
* Version Independent ID: 09008259-4b53-2925-9679-ecad59cefe41
* Content: [Tutorial - Customize Microsoft Entra attribute mappings in Application Provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/customize-application-attributes#provisioning-a-role-to-a-scim-app)
* Content Source: [docs/identity/app-provisioning/customize-application-attributes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/customize-application-attributes.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment] 2024-02-16 03:29
@music 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by music** [comment] 2024-02-16 17:44
@AjayBathini-MSFT the documentation for provisioning a role to a SCIM app can be found [here](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/customize-application-attributes#provisioning-a-role-to-a-scim-app). Specifically, this section says the role types can be custom mapped:
<img width="880" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/14796123/351aa902-6dd0-4ee2-978b-9e9c550a8d20">

**Comment by Naveenommi-MSFT** [comment] 2024-02-18 03:47
@music 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment] 2024-02-18 04:49
Hello @music 
Thank you for bringing this to our attention. Based on the information you provided, it appears that there may be an inconsistency in the behavior of the SingleAppRoleAssignment expression when mapping to the `roles[primary eq "True"].type` and `roles[primary eq "True"].value` attributes.

To clarify, the `roles[primary eq "True"].type` attribute is used to specify the type of the role, while the `roles[primary eq "True"].value` attribute is used to specify the value of the role. 

It's possible that the `roles[primary eq "True"].type` attribute is not writable, or that it is being overwritten by another setting. However, without more information about your specific configuration, it's difficult to determine the cause of this behavior.

I recommend reaching out to [Microsoft support](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) for further assistance with this issue. They can help you troubleshoot the issue and determine if this is a bug on the Entra side.

**Comment by Naveenommi-MSFT** [comment] 2024-02-20 05:13
@music 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close

**Closed by Naveenommi-MSFT** 2024-02-20 05:13 UTC
Labels: cxp, triaged, awaiting-customer-response, app-provisioning/subsvc, doc-bug, Pri3, entra-id/svc
