### ISSUE TITLE
Provisioning multi-valued attribute with API Driven Inbound Provisioning Bulk Upload fails

### ISSUE THREAD

**Issue by MithunChopda** [MicrosoftDocs/entra-docs#71] opened 2023-12-14 08:18 UTC
I have setup an API Driven Inbound Provisioning app and a Client app. I added a custom attribute of type string with multi-valued ON.

The value for this multi-valued attribute is sent in Bulk Upload as below
        "urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User": {
          "HireDate": "2022-07-01",
          "SecondarySubjects": [
                {
                       "subject":"Maths",
                        "startDate": "2023-01-01",
                        "endDate": "2024-12-31"
                },
                {
                       "subject":"History",
                        "startDate": "2023-01-01",
                        "endDate": "2024-12-31"
                }
          ]

The provisioning logs report the following error in Troubleshoot & Recommendations tab.

Export of the object with id = <removed> and joining property = <removed> to the Microsoft Online Directory Service failed. Reason: Content-Type: multipart/mixed; boundary=changesetresponse_b049bae6-8d90-4eca-b0d8-f582286addc3 --changesetresponse_b049bae6-8d90-4eca-b0d8-f582286addc3 Content-Type: application/http Content-Transfer-Encoding: binary HTTP/1.1 400 Bad Request Content-ID: 2 DataServiceVersion: 3.0; Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8 {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"**A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.**"}}} --changesetresponse_b049bae6-8d90-4eca-b0d8-f582286addc3-- . This operation was retried 0 times. It will be retried again after this date: 2023-12-14T07:53:02.8100328Z UTC

Changing the payload to continues to throw the same error

        "urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User": {
          "HireDate": "2022-07-01",
          "SecondarySubjects": [
                  "Maths","History"
          ]

The custom attributes are mapped correctly in Source and Target list.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b07a9e-5e16-32ed-265e-32a32998ce37
* Version Independent ID: 09008259-4b53-2925-9679-ecad59cefe41
* Content: [Tutorial - Customize Microsoft Entra attribute mappings in Application Provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/customize-application-attributes)
* Content Source: [docs/identity/app-provisioning/customize-application-attributes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/customize-application-attributes.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SaibabaBalapur-MSFT** [comment] 2023-12-14 16:54
@MithunChopda 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment] 2023-12-15 12:51
@MithunChopda 
In your first example, the payload includes type information for each value in the SecondarySubjects array, so it should be valid. However, the error message suggests that the type information may not be correctly formatted or included in the payload.

In your second example, the payload does not include any type information for the SecondarySubjects array, which is likely the cause of the error. To fix this, you can include the type information for each value in the array using the following format:

```
"SecondarySubjects": [
  {
    "$ref": "urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:Subject",
    "value": "Maths"
  },
  {
    "$ref": "urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:Subject",
    "value": "History"
  }
]
```

This format includes a $ref property that specifies the type of the value, and a value property that contains the actual value. You can replace urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:Subject with the appropriate type name for your custom attribute.

I hope this helps! if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by MithunChopda** [comment] 2023-12-17 20:30
Thank you, @Naveenommi-MSFT for quick response. I will try this.

**Comment by Naveenommi-MSFT** [comment] 2023-12-18 14:03
@MithunChopda 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close

**Closed by Naveenommi-MSFT** 2023-12-18 14:03 UTC
Labels: cxp, triaged, active-directory/svc, product-question, Pri1, awaiting-customer-response, app-provisioning/subsvc
