### ISSUE TITLE
Clarification on FIDO2 support status

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/entra-docs#24] opened 2023-12-05 22:30 UTC
The page at https://learn.microsoft.com/en-us/entra/identity/authentication/fido2-compatibility details FIDO2 combability with iOS and Android, however this page seems to have an outdated statement:

`As of February 2021, FIDO2 is not currently supported for native iOS or Android apps, but it is in development.`

Is there any newer guidance?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f22cc9c-eabe-842d-1606-9725ddd69d73
* Version Independent ID: b0bcebe2-07f0-2bd9-3e26-eb5553d9838a
* Content: [Support passwordless authentication with FIDO2 keys in apps you develop - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/support-fido2-authentication)
* Content Source: [docs/identity-platform/support-fido2-authentication.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/support-fido2-authentication.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by RamanathanChinnappan-MSFT** [comment] 2023-12-06 05:24
@bubbletroubles 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment] 2023-12-08 05:40
@bubbletroubles 
I apologize for the confusion. The statement on the page you mentioned is outdated and no longer accurate. 

As of September 2021, FIDO2 is supported on native iOS and Android apps. Microsoft has released the Microsoft Authenticator app for iOS and Android, which supports FIDO2 authentication. 

You can find more information about FIDO2 compatibility with Microsoft products on the following page: https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-passwordless#fido2-security-keys

I apologize for any confusion caused by the outdated information on the page you mentioned. We will work to update the page with the latest information.

**Comment by ManoharLakkoju-MSFT** [comment] 2023-12-08 05:41
@henrymbuguakiarie
Could you Please review this and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment] 2023-12-11 03:52
@bubbletroubles 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation

**Closed by ManoharLakkoju-MSFT** 2023-12-11 03:52 UTC
Labels: cxp, triaged, doc-enhancement, active-directory/svc, Pri2, develop/subsvc, awaiting-customer-response
