### ISSUE TITLE
Explain what OnPremisesSuccessCloudFailure means and when this occurs

### ISSUE THREAD

**Issue by calazlo** [MicrosoftDocs/entra-docs#694] opened 2024-04-22 14:09 UTC
Hi,

Can you please document what this code means?

 "result": "success",
  "resultReason": "OnPremisesSuccessCloudFailure",

-> my understanding is that we are treating this as a successful password reset for reporting purposes
-> my understanding is that  It usually happens when the customer is using a password which meets the on-premises password policy, but it doesn't meet the AAD password policies.
Due to the source of authority for this user, the password will be written in AD. 
https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-policy#microsoft-entra-password-policies
***it would be nice to have also documented the logic why this error code appears when the Authentication method is PTA and PHS is only the optional feature.
 
***keep in mind that the "Failure" with the "success" are a bit confusing :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9aa3da3-eafd-23ea-91dd-569fceebfd05
* Version Independent ID: 71acb3c7-7a3a-5d6c-c397-2c14450cf9f0
* Content: [Troubleshoot self-service password reset - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/troubleshoot-sspr)
* Content Source: [docs/identity/authentication/troubleshoot-sspr.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/troubleshoot-sspr.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment] 2024-04-22 16:27
@calazlo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment] 2024-04-26 10:14
@calazlo 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by Justinha** [comment] 2024-05-10 21:18
@calazlo sorry for delay. Here's what I learned, and I'll add to the topic:
OnPremisesSuccessCloudFailure

User message: We've reset your password successfully, but you'll have to wait a few minutes before the changes are committed to the cloud. After these changes are committed, you'll be able to use your new password wherever you sign in with a work or school account. 

It means password reset was successful on-premises, but there was an error while writing to the cloud. The error might be caused by a timeout, or a cloud password policy, throttling, or other reasons.

**Comment by Justinha** [comment] 2024-05-11 00:46
#please-close

**Closed by Justinha** 2024-05-11 00:46 UTC
Labels: triaged, product-question, assigned-to-author, Pri1, authentication/subsvc, entra-id/svc
