### ISSUE TITLE
Broken Links to downloads

### ISSUE THREAD

**Issue by ryoung-skircr** [MicrosoftDocs/entra-docs#915] opened 2024-06-05 19:49 UTC
It would appear that most if not all of the links to the downloads on this page are broken for the DC agents etc.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23e000f0-84ce-7ec7-e5ed-4bd9c49f5d49
* Version Independent ID: e636b9d1-be81-0f00-97c4-ff4fa9078be3
* Content: [Deploy on-premises Microsoft Entra Password Protection - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-ban-bad-on-premises-deploy)
* Content Source: [docs/identity/authentication/howto-password-ban-bad-on-premises-deploy.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-password-ban-bad-on-premises-deploy.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by CelesteDG** [comment] 2024-06-05 20:09
#reassign:@justinha

**Comment by TPavanBalaji** [comment] 2024-06-06 04:22
@ryoung-skircr 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by Justinha** [comment] 2024-06-19 22:36
@ryoung-skircr Thanks for the feedback. I can't reproduce a broken link to the Download Center. The link is https://www.microsoft.com/en-us/download/details.aspx?id=57071. #please-close

**Closed by Justinha** 2024-06-19 22:36 UTC
Labels: triaged, assigned-to-author, Pri1, authentication/subsvc, doc-bug, entra-id/svc
