### ISSUE TITLE
Guest Inviter have undocumented limitations on GDAP.

### ISSUE THREAD

**Issue by adrienmaugard** [MicrosoftDocs/entra-docs#56] opened 2023-12-12 11:45 UTC
Hello

About https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#guest-inviter
We had to open a support request as this Role have some explicit deny or undocumented documentations.

As discussed elsewhere https://techcommunity.microsoft.com/t5/partner-led-tech-topics/getting-403-quot-insufficient-privileges-to-complete-the/m-p/4005729

If you assign the Guest Inviter on a user who already have User Administrator, it break the User Administrator role.
You cannot access the user profil or edit the user profile data in EntraID until you remove the Guest Inviter role.

Can you also write the restriction this role have in addition to its explicit rights in the documentation?

It's mainly for GDAP, not tester from within the tenant itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0767aac4-fcd9-eaac-2c30-8f17d8eadd92
* Version Independent ID: a380a828-03f9-e037-3a62-e4165fda7cb6
* Content: [Microsoft Entra built-in roles - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference)
* Content Source: [docs/identity/role-based-access-control/permissions-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/permissions-reference.md)
* Service: **active-directory**
* Sub-service: **roles**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by Naveenommi-MSFT** [comment] 2023-12-12 17:35
@adrienmaugard 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment] 2023-12-15 23:47
@adrienmaugard 
I'm going to assign this to the document author so they can take a look at it accordingly

@rolyon 
Could you Please review this and update as appropriate.

**Comment by AtleeRRN** [comment] 2024-01-02 15:52
Is this intended behavior?

**Comment by rolyon** [comment] 2024-02-07 20:32
Hi @adrienmaugard
Thanks for your feedback. We shared your feedback with the team and they made an update.
Can you try assigning these roles again? This scenario should be working now.
thanks

**Comment by AtleeRRN** [comment] 2024-02-07 21:43
That worked for me, is their a changelog for GDAP/Partner Portal?

**Comment by rolyon** [comment] 2024-02-12 22:07
I don't have any additional details. Let us know if you have any additional feedback.
thanks

**Comment by rolyon** [comment] 2024-02-12 22:08
#please-close

**Closed by rolyon** 2024-02-12 22:08 UTC
Labels: triaged, doc-enhancement, active-directory/svc, assigned-to-author, Pri1, roles/subsvc
